-- 사용자 생성
CREATE USER C##outven IDENTIFIED BY m1234;

-- 사용자 생성 확인
SELECT USERNAME, ACCOUNT_STATUS FROM DBA_USERS

-- 권한 부여
GRANT CREATE TABLE TO C##outven;
GRANT CREATE VIEW TO C##outven;
GRANT CREATE SEQUENCE TO C##outven;
GRANT CREATE SESSION TO C##outven;

commit
